export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  CHURCH_ADMIN = 'CHURCH_ADMIN',
  CHURCH_LEADER = 'CHURCH_LEADER',
  PASTOR = 'PASTOR',
  ASSISTANT_PASTOR = 'ASSISTANT_PASTOR',
  BACKGROUND_CHECKER = 'BACKGROUND_CHECKER',
  HELPER = 'HELPER',
  CHURCH_MEMBER = 'CHURCH_MEMBER',
  PRO_USER = 'PRO_USER',
  USER = 'USER',
}
